//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTMEntities : DbContext
    {
        public PTMEntities()
            : base("name=PTMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_BaseRole> Tbl_BaseRole { get; set; }
        public virtual DbSet<Tbl_Client> Tbl_Client { get; set; }
        public virtual DbSet<Tbl_Code> Tbl_Code { get; set; }
        public virtual DbSet<Tbl_CodeGroup> Tbl_CodeGroup { get; set; }
        public virtual DbSet<Tbl_ContactUs> Tbl_ContactUs { get; set; }
        public virtual DbSet<Tbl_Document> Tbl_Document { get; set; }
        public virtual DbSet<Tbl_Login> Tbl_Login { get; set; }
        public virtual DbSet<Tbl_LoginToken> Tbl_LoginToken { get; set; }
        public virtual DbSet<Tbl_Partner> Tbl_Partner { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<Tbl_Slider> Tbl_Slider { get; set; }
        public virtual DbSet<Tbl_SMSProviderConfiguration> Tbl_SMSProviderConfiguration { get; set; }
        public virtual DbSet<Tbl_SMSProviderNumber> Tbl_SMSProviderNumber { get; set; }
        public virtual DbSet<Tbl_SMSResponse> Tbl_SMSResponse { get; set; }
        public virtual DbSet<Tbl_SMSSetting> Tbl_SMSSetting { get; set; }
        public virtual DbSet<Tbl_SMSTemplate> Tbl_SMSTemplate { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_Video> Tbl_Video { get; set; }
    }
}
