//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Slider
    {
        public int Slider_ID { get; set; }
        public System.Guid Slider_Guid { get; set; }
        public int Slider_LoginID { get; set; }
        public int Slider_DocumentID { get; set; }
        public string Slider_Tital { get; set; }
        public string Slider_Subject { get; set; }
        public string Slider_Description { get; set; }
        public string Slider_Link { get; set; }
        public bool Slider_IsActive { get; set; }
        public bool Slider_IsDelete { get; set; }
        public System.DateTime Slider_CreateDate { get; set; }
        public System.DateTime Slider_ModifyDate { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
    }
}
