//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Video
    {
        public int Video_ID { get; set; }
        public System.Guid Video_Guid { get; set; }
        public int Video_LoginID { get; set; }
        public int Video_DocumentID { get; set; }
        public string Video_Titel { get; set; }
        public System.DateTime Video_CreateDate { get; set; }
        public bool Video_IsActive { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
    }
}
