//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Document()
        {
            this.Tbl_Client = new HashSet<Tbl_Client>();
            this.Tbl_Partner = new HashSet<Tbl_Partner>();
            this.Tbl_Product = new HashSet<Tbl_Product>();
            this.Tbl_Slider = new HashSet<Tbl_Slider>();
            this.Tbl_Video = new HashSet<Tbl_Video>();
        }
    
        public int Document_ID { get; set; }
        public System.Guid Document_Guid { get; set; }
        public int Document_LoginID { get; set; }
        public int Document_TypeCodeID { get; set; }
        public string Document_Path { get; set; }
        public string Document_FolderName { get; set; }
        public string Document_FileName { get; set; }
        public System.DateTime Document_CreateDate { get; set; }
        public bool Document_IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Client> Tbl_Client { get; set; }
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Partner> Tbl_Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Slider> Tbl_Slider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Video> Tbl_Video { get; set; }
    }
}
