//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Client
    {
        public int Client_ID { get; set; }
        public System.Guid Client_Guid { get; set; }
        public int Client_LoginID { get; set; }
        public int Client_DocumentID { get; set; }
        public string Client_Titel { get; set; }
        public string Client_Link { get; set; }
        public bool Client_IsActive { get; set; }
        public System.DateTime Client_CreateDate { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
    }
}
