//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BaseRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BaseRole()
        {
            this.Tbl_Login = new HashSet<Tbl_Login>();
        }
    
        public int BR_ID { get; set; }
        public Nullable<System.Guid> BR_Guid { get; set; }
        public string BR_Name { get; set; }
        public string BR_Display { get; set; }
        public Nullable<System.DateTime> BR_CreateDate { get; set; }
        public Nullable<System.DateTime> BR_ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Login> Tbl_Login { get; set; }
    }
}
