//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoginToken
    {
        public int LT_ID { get; set; }
        public System.Guid LT_Guid { get; set; }
        public int LT_LoginID { get; set; }
        public int LT_TypeCodeID { get; set; }
        public string LT_Key { get; set; }
        public System.DateTime LT_CreateDate { get; set; }
        public System.DateTime LT_ExpDate { get; set; }
        public bool LT_Expired { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
    }
}
