//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMGroup.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int Product_ID { get; set; }
        public System.Guid Product_Guid { get; set; }
        public int Product_LoginID { get; set; }
        public int Product_DocumentID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Subject { get; set; }
        public string Product_Abstract { get; set; }
        public string Product_Description { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_Login Tbl_Login { get; set; }
    }
}
